# Generated by Django 3.0 on 2020-10-01 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='dn_header_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn_no', models.CharField(max_length=20)),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('trip_no', models.CharField(max_length=10)),
                ('promised_date', models.DateField(verbose_name='Promised Date')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('telephone', models.CharField(max_length=10, verbose_name='Telephone')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='master_package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_no', models.CharField(max_length=10)),
                ('package_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='po_header_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(max_length=20, verbose_name='Purchase Order No.')),
            ],
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sup_no', models.CharField(max_length=20, verbose_name='Supplier No.')),
                ('sup_name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_no', models.CharField(max_length=10, verbose_name='Truck no.')),
            ],
        ),
        migrations.CreateModel(
            name='truck_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='truck_list_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_no', models.CharField(max_length=5, verbose_name='No.')),
                ('remark', models.TextField(null=True, verbose_name='Remark')),
                ('destination', models.CharField(max_length=200, verbose_name='Destination')),
                ('delivery_date', models.DateField(max_length=200, verbose_name='Delivery Date')),
                ('delivery_note_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.dn_header_report', verbose_name='Delivery Note no.')),
            ],
        ),
        migrations.CreateModel(
            name='truck_header_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_control_no', models.CharField(max_length=20, verbose_name='Truck Control No.')),
                ('promised_date', models.DateField(verbose_name='Promised Date')),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.employee')),
                ('list_id', models.ManyToManyField(to='blog.truck_list_report')),
                ('truck_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.truck')),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.truck_type', verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='replacement_list_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_no', models.CharField(max_length=5, verbose_name='No.')),
                ('replacement', models.IntegerField(verbose_name='Replacement Qty.')),
                ('receive', models.IntegerField(verbose_name='Receive Qty.')),
                ('remark', models.TextField(null=True, verbose_name='Remark')),
                ('dn_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.dn_header_report', verbose_name='Ref. DN No.')),
                ('package_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.master_package', verbose_name='Package Code')),
                ('po_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.po_header_report', verbose_name='MST PO No.')),
                ('sup_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.supplier', verbose_name='Supplier Code')),
            ],
        ),
        migrations.CreateModel(
            name='replacement_header_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_no', models.CharField(max_length=20)),
                ('replacement_date', models.DateField(verbose_name='Replacement Date')),
                ('replacement_list', models.ManyToManyField(to='blog.replacement_list_report')),
            ],
        ),
        migrations.CreateModel(
            name='dn_list_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_no', models.CharField(max_length=5, verbose_name='No.')),
                ('order_no', models.CharField(max_length=5, verbose_name='Order No.')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('actual', models.IntegerField(verbose_name='Actual')),
                ('remark', models.TextField(max_length=200, verbose_name='Remark')),
                ('package_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.master_package', verbose_name='Package Code')),
            ],
        ),
        migrations.AddField(
            model_name='dn_header_report',
            name='dn_list',
            field=models.ManyToManyField(to='blog.dn_list_report'),
        ),
        migrations.AddField(
            model_name='dn_header_report',
            name='driver_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.employee'),
        ),
        migrations.AddField(
            model_name='dn_header_report',
            name='truck_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.truck'),
        ),
    ]
