# Generated by Django 3.0 on 2020-09-22 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10, verbose_name='Delivery Note no.')),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('telephone', models.CharField(max_length=10, verbose_name='Telephone')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.department', verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_no', models.CharField(max_length=10, verbose_name='Truck no.')),
            ],
        ),
        migrations.CreateModel(
            name='truck_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='truck_list_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_no', models.CharField(max_length=5, verbose_name='No.')),
                ('remark', models.TextField(null=True, verbose_name='Remark')),
                ('destination', models.CharField(max_length=200, verbose_name='Destination')),
                ('delivery_date', models.DateField(max_length=200, verbose_name='Delivery Date')),
                ('delivery_note_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.delivery_note')),
            ],
        ),
        migrations.CreateModel(
            name='truck_header_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_control_no', models.CharField(max_length=5, verbose_name='Truck Control No.')),
                ('promised_date', models.DateField()),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.truck_list_report')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.employee')),
                ('truck_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.truck')),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.truck_type', verbose_name='Type'),
        ),
    ]
