# Generated by Django 3.0 on 2020-09-28 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck_header_report',
            old_name='name',
            new_name='driver_name',
        ),
        migrations.AddField(
            model_name='truck_header_report',
            name='truck_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.truck_type', verbose_name='Truck Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dn_header_report',
            name='truck_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.truck_type', verbose_name='Truck Type'),
        ),
    ]
