# Generated by Django 3.0 on 2020-09-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='master_package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_no', models.CharField(max_length=10)),
                ('package_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='dn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn_no', models.CharField(max_length=5)),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('promised_date', models.DateField(verbose_name='Promised Date')),
                ('seq', models.IntegerField(verbose_name='No.')),
                ('order_no', models.CharField(max_length=5, verbose_name='Order No.')),
                ('package_code', models.CharField(max_length=10, verbose_name='Package Code')),
                ('package_name', models.CharField(max_length=50, verbose_name='Package Code')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('actual', models.IntegerField(verbose_name='Actual')),
                ('remark', models.TextField(max_length=200, verbose_name='Remark')),
                ('driver_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.employee')),
            ],
        ),
    ]
