# Generated by Django 3.0 on 2020-09-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200928_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dn_header_report',
            name='truck_type',
        ),
        migrations.RemoveField(
            model_name='truck_header_report',
            name='truck_type',
        ),
    ]
