# Generated by Django 3.0 on 2020-09-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_dn_master_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dn',
            name='package_code',
        ),
        migrations.RemoveField(
            model_name='dn',
            name='package_name',
        ),
        migrations.AddField(
            model_name='dn',
            name='package_no',
            field=models.ManyToManyField(max_length=10, to='blog.master_package', verbose_name='Package Code'),
        ),
    ]
