# Generated by Django 3.0 on 2020-09-28 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200928_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck_list_report',
            name='delivery_note_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.dn_header_report', verbose_name='Delivery Note no.'),
        ),
        migrations.DeleteModel(
            name='delivery_note',
        ),
    ]
