# Generated by Django 3.0 on 2020-09-26 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200926_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dn',
            name='package_no',
        ),
        migrations.AddField(
            model_name='dn',
            name='package_no',
            field=models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='blog.master_package', verbose_name='Package Code'),
            preserve_default=False,
        ),
    ]
