# Generated by Django 3.0 on 2020-09-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200926_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dn',
            name='package_no',
        ),
        migrations.AddField(
            model_name='dn',
            name='package_no',
            field=models.ManyToManyField(to='blog.master_package', verbose_name='Package Code'),
        ),
    ]
