# Generated by Django 3.0 on 2020-09-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_dn_header_report_trip_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dn_header_report',
            name='dn_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='truck_header_report',
            name='truck_control_no',
            field=models.CharField(max_length=20, verbose_name='Truck Control No.'),
        ),
    ]
