# Generated by Django 3.0 on 2020-09-28 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200926_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dn',
            new_name='dn_header',
        ),
        migrations.RenameField(
            model_name='dn_list',
            old_name='no',
            new_name='list_no',
        ),
    ]
