# Generated by Django 3.0 on 2020-09-28 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200928_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dn_list',
            name='package_no',
        ),
        migrations.AddField(
            model_name='dn_list',
            name='package_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.master_package', verbose_name='Package Code'),
            preserve_default=False,
        ),
    ]
