# Generated by Django 3.0 on 2020-09-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200928_1001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dn_header',
            new_name='dn_header_report',
        ),
        migrations.RenameModel(
            old_name='dn_list',
            new_name='dn_list_report',
        ),
    ]
