# Generated by Django 3.0 on 2020-09-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200928_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dn_list_report',
            name='list_no',
            field=models.CharField(max_length=5, verbose_name='No.'),
        ),
    ]
