# Generated by Django 3.0 on 2020-09-28 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200928_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dn_list_report',
            name='package_no',
        ),
        migrations.AddField(
            model_name='dn_list_report',
            name='package_no',
            field=models.ManyToManyField(to='blog.master_package', verbose_name='Package Code'),
        ),
    ]
