# Generated by Django 3.0 on 2020-09-28 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200928_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dn_header_report',
            old_name='driver_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='dn_header_report',
            name='delivery_date',
        ),
        migrations.AddField(
            model_name='dn_header_report',
            name='truck_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.truck'),
            preserve_default=False,
        ),
    ]
